//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wikiService.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountService
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Token { get; set; }
        public int IDASR { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual AccountServiceRole AccountServiceRole { get; set; }
    }
}
