//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiManageWeb.WikiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaiKhoan", Namespace="http://schemas.datacontract.org/2004/07/wikiService.Models.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRole {
            get {
                return this.IDRoleField;
            }
            set {
                if ((this.IDRoleField.Equals(value) != true)) {
                    this.IDRoleField = value;
                    this.RaisePropertyChanged("IDRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTaiKhoan {
            get {
                return this.MaTaiKhoanField;
            }
            set {
                if ((this.MaTaiKhoanField.Equals(value) != true)) {
                    this.MaTaiKhoanField = value;
                    this.RaisePropertyChanged("MaTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTaiKhoan {
            get {
                return this.TenTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTaiKhoanField, value) != true)) {
                    this.TenTaiKhoanField = value;
                    this.RaisePropertyChanged("TenTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMuc", Namespace="http://schemas.datacontract.org/2004/07/wikiService.Models.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class DanhMuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoSanphamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDanhMuc {
            get {
                return this.MaDanhMucField;
            }
            set {
                if ((this.MaDanhMucField.Equals(value) != true)) {
                    this.MaDanhMucField = value;
                    this.RaisePropertyChanged("MaDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoSanpham {
            get {
                return this.SoSanphamField;
            }
            set {
                if ((this.SoSanphamField.Equals(value) != true)) {
                    this.SoSanphamField = value;
                    this.RaisePropertyChanged("SoSanpham");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaiViet", Namespace="http://schemas.datacontract.org/2004/07/wikiService.Models.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class BaiViet : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WikiManageWeb.WikiService.LichSuBinhLuan BinhLuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WikiManageWeb.WikiService.DanhMuc DanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WikiManageWeb.WikiService.LichSuBinhLuan[] DanhSachBinhLuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaBaiVietField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayTaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WikiManageWeb.WikiService.TaiKhoan NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SoBinhLuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TieuDeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WikiManageWeb.WikiService.LichSuBinhLuan BinhLuan {
            get {
                return this.BinhLuanField;
            }
            set {
                if ((object.ReferenceEquals(this.BinhLuanField, value) != true)) {
                    this.BinhLuanField = value;
                    this.RaisePropertyChanged("BinhLuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WikiManageWeb.WikiService.DanhMuc DanhMuc {
            get {
                return this.DanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.DanhMucField, value) != true)) {
                    this.DanhMucField = value;
                    this.RaisePropertyChanged("DanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WikiManageWeb.WikiService.LichSuBinhLuan[] DanhSachBinhLuan {
            get {
                return this.DanhSachBinhLuanField;
            }
            set {
                if ((object.ReferenceEquals(this.DanhSachBinhLuanField, value) != true)) {
                    this.DanhSachBinhLuanField = value;
                    this.RaisePropertyChanged("DanhSachBinhLuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaBaiViet {
            get {
                return this.MaBaiVietField;
            }
            set {
                if ((this.MaBaiVietField.Equals(value) != true)) {
                    this.MaBaiVietField = value;
                    this.RaisePropertyChanged("MaBaiViet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDanhMuc {
            get {
                return this.MaDanhMucField;
            }
            set {
                if ((this.MaDanhMucField.Equals(value) != true)) {
                    this.MaDanhMucField = value;
                    this.RaisePropertyChanged("MaDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayTao {
            get {
                return this.NgayTaoField;
            }
            set {
                if ((this.NgayTaoField.Equals(value) != true)) {
                    this.NgayTaoField = value;
                    this.RaisePropertyChanged("NgayTao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WikiManageWeb.WikiService.TaiKhoan NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiDung {
            get {
                return this.NoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiDungField, value) != true)) {
                    this.NoiDungField = value;
                    this.RaisePropertyChanged("NoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SoBinhLuan {
            get {
                return this.SoBinhLuanField;
            }
            set {
                if ((this.SoBinhLuanField.Equals(value) != true)) {
                    this.SoBinhLuanField = value;
                    this.RaisePropertyChanged("SoBinhLuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenNguoiDung {
            get {
                return this.TenNguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.TenNguoiDungField, value) != true)) {
                    this.TenNguoiDungField = value;
                    this.RaisePropertyChanged("TenNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TieuDe {
            get {
                return this.TieuDeField;
            }
            set {
                if ((object.ReferenceEquals(this.TieuDeField, value) != true)) {
                    this.TieuDeField = value;
                    this.RaisePropertyChanged("TieuDe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LichSuBinhLuan", Namespace="http://schemas.datacontract.org/2004/07/wikiService.Models.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class LichSuBinhLuan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaBaiVietField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaBinhLuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaNguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NgayCapNhatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WikiManageWeb.WikiService.TaiKhoan NguoiDungField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiDungBinhLuanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaBaiViet {
            get {
                return this.MaBaiVietField;
            }
            set {
                if ((this.MaBaiVietField.Equals(value) != true)) {
                    this.MaBaiVietField = value;
                    this.RaisePropertyChanged("MaBaiViet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaBinhLuan {
            get {
                return this.MaBinhLuanField;
            }
            set {
                if ((this.MaBinhLuanField.Equals(value) != true)) {
                    this.MaBinhLuanField = value;
                    this.RaisePropertyChanged("MaBinhLuan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaNguoiDung {
            get {
                return this.MaNguoiDungField;
            }
            set {
                if ((this.MaNguoiDungField.Equals(value) != true)) {
                    this.MaNguoiDungField = value;
                    this.RaisePropertyChanged("MaNguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NgayCapNhat {
            get {
                return this.NgayCapNhatField;
            }
            set {
                if ((this.NgayCapNhatField.Equals(value) != true)) {
                    this.NgayCapNhatField = value;
                    this.RaisePropertyChanged("NgayCapNhat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WikiManageWeb.WikiService.TaiKhoan NguoiDung {
            get {
                return this.NguoiDungField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiDungField, value) != true)) {
                    this.NguoiDungField = value;
                    this.RaisePropertyChanged("NguoiDung");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoiDungBinhLuan {
            get {
                return this.NoiDungBinhLuanField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiDungBinhLuanField, value) != true)) {
                    this.NoiDungBinhLuanField = value;
                    this.RaisePropertyChanged("NoiDungBinhLuan");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WikiService.DichVuWiki")]
    public interface DichVuWiki {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangNhap", ReplyAction="http://tempuri.org/DichVuWiki/DangNhapResponse")]
        int DangNhap(WikiManageWeb.WikiService.TaiKhoan userCaContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangNhap", ReplyAction="http://tempuri.org/DichVuWiki/DangNhapResponse")]
        System.Threading.Tasks.Task<int> DangNhapAsync(WikiManageWeb.WikiService.TaiKhoan userCaContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdmin", ReplyAction="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdminResponse")]
        bool DangKiTaiKhoanAdmin(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdmin", ReplyAction="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdminResponse")]
        System.Threading.Tasks.Task<bool> DangKiTaiKhoanAdminAsync(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraiTaiKhoanDatontai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraiTaiKhoanDatontaiResponse")]
        bool KiemTraiTaiKhoanDatontai(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraiTaiKhoanDatontai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraiTaiKhoanDatontaiResponse")]
        System.Threading.Tasks.Task<bool> KiemTraiTaiKhoanDatontaiAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTaiKhoan", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTaiKhoanResponse")]
        WikiManageWeb.WikiService.TaiKhoan KiemTraTaiKhoan(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTaiKhoan", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTaiKhoanResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.TaiKhoan> KiemTraTaiKhoanAsync(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachDanhMucResponse")]
        WikiManageWeb.WikiService.DanhMuc[] DanhSachDanhMuc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachDanhMucResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.DanhMuc[]> DanhSachDanhMucAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ThemMoiDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ThemMoiDanhMucResponse")]
        bool ThemMoiDanhMuc(WikiManageWeb.WikiService.DanhMuc category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ThemMoiDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ThemMoiDanhMucResponse")]
        System.Threading.Tasks.Task<bool> ThemMoiDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraDanhMucDaTonTai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraDanhMucDaTonTaiResponse")]
        bool KiemTraDanhMucDaTonTai(string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraDanhMucDaTonTai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraDanhMucDaTonTaiResponse")]
        System.Threading.Tasks.Task<bool> KiemTraDanhMucDaTonTaiAsync(string categoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ChitTietDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ChitTietDanhMucResponse")]
        WikiManageWeb.WikiService.DanhMuc ChitTietDanhMuc(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ChitTietDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ChitTietDanhMucResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.DanhMuc> ChitTietDanhMucAsync(int idCategory);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/SuaDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/SuaDanhMucResponse")]
        bool SuaDanhMuc(WikiManageWeb.WikiService.DanhMuc category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/SuaDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/SuaDanhMucResponse")]
        System.Threading.Tasks.Task<bool> SuaDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/XoaDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/XoaDanhMucResponse")]
        bool XoaDanhMuc(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/XoaDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/XoaDanhMucResponse")]
        System.Threading.Tasks.Task<bool> XoaDanhMucAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietResponse")]
        WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiViet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietDaXem", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietDaXemResponse")]
        WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiVietDaXem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietDaXem", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietDaXemResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietDaXemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietChuaXem", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietChuaXemResponse")]
        WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiVietChuaXem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietChuaXem", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachTatCaBaiVietChuaXemResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietChuaXemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachBaiVietNguoiDung", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachBaiVietNguoiDungResponse")]
        WikiManageWeb.WikiService.BaiViet[] DanhSachBaiVietNguoiDung();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachBaiVietNguoiDung", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachBaiVietNguoiDungResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachBaiVietNguoiDungAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachSanPhamTheoDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachSanPhamTheoDanhMucResponse")]
        WikiManageWeb.WikiService.BaiViet[] DanhSachSanPhamTheoDanhMuc(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachSanPhamTheoDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachSanPhamTheoDanhMucResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachSanPhamTheoDanhMucAsync(int idCate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTieuDeDaTonTai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTieuDeDaTonTaiResponse")]
        bool KiemTraTieuDeDaTonTai(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTieuDeDaTonTai", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTieuDeDaTonTaiResponse")]
        System.Threading.Tasks.Task<bool> KiemTraTieuDeDaTonTaiAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/TaoBaiVietMoi", ReplyAction="http://tempuri.org/DichVuWiki/TaoBaiVietMoiResponse")]
        bool TaoBaiVietMoi(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/TaoBaiVietMoi", ReplyAction="http://tempuri.org/DichVuWiki/TaoBaiVietMoiResponse")]
        System.Threading.Tasks.Task<bool> TaoBaiVietMoiAsync(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ChiTietSanPham", ReplyAction="http://tempuri.org/DichVuWiki/ChiTietSanPhamResponse")]
        WikiManageWeb.WikiService.BaiViet ChiTietSanPham(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ChiTietSanPham", ReplyAction="http://tempuri.org/DichVuWiki/ChiTietSanPhamResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet> ChiTietSanPhamAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/SuaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/SuaBaiVietResponse")]
        bool SuaBaiViet(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/SuaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/SuaBaiVietResponse")]
        System.Threading.Tasks.Task<bool> SuaBaiVietAsync(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/CapNhatBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/CapNhatBaiVietResponse")]
        bool CapNhatBaiViet(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/CapNhatBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/CapNhatBaiVietResponse")]
        System.Threading.Tasks.Task<bool> CapNhatBaiVietAsync(WikiManageWeb.WikiService.BaiViet product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/XoaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/XoaBaiVietResponse")]
        bool XoaBaiViet(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/XoaBaiViet", ReplyAction="http://tempuri.org/DichVuWiki/XoaBaiVietResponse")]
        System.Threading.Tasks.Task<bool> XoaBaiVietAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DichVuWikiChannel : WikiManageWeb.WikiService.DichVuWiki, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DichVuWikiClient : System.ServiceModel.ClientBase<WikiManageWeb.WikiService.DichVuWiki>, WikiManageWeb.WikiService.DichVuWiki {
        
        public DichVuWikiClient() {
        }
        
        public DichVuWikiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DichVuWikiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWikiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWikiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DangNhap(WikiManageWeb.WikiService.TaiKhoan userCaContract) {
            return base.Channel.DangNhap(userCaContract);
        }
        
        public System.Threading.Tasks.Task<int> DangNhapAsync(WikiManageWeb.WikiService.TaiKhoan userCaContract) {
            return base.Channel.DangNhapAsync(userCaContract);
        }
        
        public bool DangKiTaiKhoanAdmin(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.DangKiTaiKhoanAdmin(userContract);
        }
        
        public System.Threading.Tasks.Task<bool> DangKiTaiKhoanAdminAsync(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.DangKiTaiKhoanAdminAsync(userContract);
        }
        
        public bool KiemTraiTaiKhoanDatontai(string email) {
            return base.Channel.KiemTraiTaiKhoanDatontai(email);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraiTaiKhoanDatontaiAsync(string email) {
            return base.Channel.KiemTraiTaiKhoanDatontaiAsync(email);
        }
        
        public WikiManageWeb.WikiService.TaiKhoan KiemTraTaiKhoan(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.KiemTraTaiKhoan(userContract);
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.TaiKhoan> KiemTraTaiKhoanAsync(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.KiemTraTaiKhoanAsync(userContract);
        }
        
        public WikiManageWeb.WikiService.DanhMuc[] DanhSachDanhMuc() {
            return base.Channel.DanhSachDanhMuc();
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.DanhMuc[]> DanhSachDanhMucAsync() {
            return base.Channel.DanhSachDanhMucAsync();
        }
        
        public bool ThemMoiDanhMuc(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.ThemMoiDanhMuc(category);
        }
        
        public System.Threading.Tasks.Task<bool> ThemMoiDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.ThemMoiDanhMucAsync(category);
        }
        
        public bool KiemTraDanhMucDaTonTai(string categoryName) {
            return base.Channel.KiemTraDanhMucDaTonTai(categoryName);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraDanhMucDaTonTaiAsync(string categoryName) {
            return base.Channel.KiemTraDanhMucDaTonTaiAsync(categoryName);
        }
        
        public WikiManageWeb.WikiService.DanhMuc ChitTietDanhMuc(int idCategory) {
            return base.Channel.ChitTietDanhMuc(idCategory);
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.DanhMuc> ChitTietDanhMucAsync(int idCategory) {
            return base.Channel.ChitTietDanhMucAsync(idCategory);
        }
        
        public bool SuaDanhMuc(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.SuaDanhMuc(category);
        }
        
        public System.Threading.Tasks.Task<bool> SuaDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.SuaDanhMucAsync(category);
        }
        
        public bool XoaDanhMuc(int id) {
            return base.Channel.XoaDanhMuc(id);
        }
        
        public System.Threading.Tasks.Task<bool> XoaDanhMucAsync(int id) {
            return base.Channel.XoaDanhMucAsync(id);
        }
        
        public WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiViet() {
            return base.Channel.DanhSachTatCaBaiViet();
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietAsync() {
            return base.Channel.DanhSachTatCaBaiVietAsync();
        }
        
        public WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiVietDaXem() {
            return base.Channel.DanhSachTatCaBaiVietDaXem();
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietDaXemAsync() {
            return base.Channel.DanhSachTatCaBaiVietDaXemAsync();
        }
        
        public WikiManageWeb.WikiService.BaiViet[] DanhSachTatCaBaiVietChuaXem() {
            return base.Channel.DanhSachTatCaBaiVietChuaXem();
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachTatCaBaiVietChuaXemAsync() {
            return base.Channel.DanhSachTatCaBaiVietChuaXemAsync();
        }
        
        public WikiManageWeb.WikiService.BaiViet[] DanhSachBaiVietNguoiDung() {
            return base.Channel.DanhSachBaiVietNguoiDung();
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachBaiVietNguoiDungAsync() {
            return base.Channel.DanhSachBaiVietNguoiDungAsync();
        }
        
        public WikiManageWeb.WikiService.BaiViet[] DanhSachSanPhamTheoDanhMuc(int idCate) {
            return base.Channel.DanhSachSanPhamTheoDanhMuc(idCate);
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet[]> DanhSachSanPhamTheoDanhMucAsync(int idCate) {
            return base.Channel.DanhSachSanPhamTheoDanhMucAsync(idCate);
        }
        
        public bool KiemTraTieuDeDaTonTai(string title) {
            return base.Channel.KiemTraTieuDeDaTonTai(title);
        }
        
        public System.Threading.Tasks.Task<bool> KiemTraTieuDeDaTonTaiAsync(string title) {
            return base.Channel.KiemTraTieuDeDaTonTaiAsync(title);
        }
        
        public bool TaoBaiVietMoi(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.TaoBaiVietMoi(product);
        }
        
        public System.Threading.Tasks.Task<bool> TaoBaiVietMoiAsync(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.TaoBaiVietMoiAsync(product);
        }
        
        public WikiManageWeb.WikiService.BaiViet ChiTietSanPham(int id) {
            return base.Channel.ChiTietSanPham(id);
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.BaiViet> ChiTietSanPhamAsync(int id) {
            return base.Channel.ChiTietSanPhamAsync(id);
        }
        
        public bool SuaBaiViet(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.SuaBaiViet(product);
        }
        
        public System.Threading.Tasks.Task<bool> SuaBaiVietAsync(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.SuaBaiVietAsync(product);
        }
        
        public bool CapNhatBaiViet(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.CapNhatBaiViet(product);
        }
        
        public System.Threading.Tasks.Task<bool> CapNhatBaiVietAsync(WikiManageWeb.WikiService.BaiViet product) {
            return base.Channel.CapNhatBaiVietAsync(product);
        }
        
        public bool XoaBaiViet(int id) {
            return base.Channel.XoaBaiViet(id);
        }
        
        public System.Threading.Tasks.Task<bool> XoaBaiVietAsync(int id) {
            return base.Channel.XoaBaiVietAsync(id);
        }
    }
}
