//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WikiManageWeb.WikiService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaiKhoan", Namespace="http://schemas.datacontract.org/2004/07/wikiService.Models.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class TaiKhoan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDRoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MatKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenTaiKhoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrangThaiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDRole {
            get {
                return this.IDRoleField;
            }
            set {
                if ((this.IDRoleField.Equals(value) != true)) {
                    this.IDRoleField = value;
                    this.RaisePropertyChanged("IDRole");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaTaiKhoan {
            get {
                return this.MaTaiKhoanField;
            }
            set {
                if ((this.MaTaiKhoanField.Equals(value) != true)) {
                    this.MaTaiKhoanField = value;
                    this.RaisePropertyChanged("MaTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MatKhau {
            get {
                return this.MatKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.MatKhauField, value) != true)) {
                    this.MatKhauField = value;
                    this.RaisePropertyChanged("MatKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenTaiKhoan {
            get {
                return this.TenTaiKhoanField;
            }
            set {
                if ((object.ReferenceEquals(this.TenTaiKhoanField, value) != true)) {
                    this.TenTaiKhoanField = value;
                    this.RaisePropertyChanged("TenTaiKhoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrangThai {
            get {
                return this.TrangThaiField;
            }
            set {
                if ((this.TrangThaiField.Equals(value) != true)) {
                    this.TrangThaiField = value;
                    this.RaisePropertyChanged("TrangThai");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DanhMuc", Namespace="http://schemas.datacontract.org/2004/07/wikiService.ModelViewContract")]
    [System.SerializableAttribute()]
    public partial class DanhMuc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaDanhMucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenDanhMucField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaDanhMuc {
            get {
                return this.MaDanhMucField;
            }
            set {
                if ((this.MaDanhMucField.Equals(value) != true)) {
                    this.MaDanhMucField = value;
                    this.RaisePropertyChanged("MaDanhMuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenDanhMuc {
            get {
                return this.TenDanhMucField;
            }
            set {
                if ((object.ReferenceEquals(this.TenDanhMucField, value) != true)) {
                    this.TenDanhMucField = value;
                    this.RaisePropertyChanged("TenDanhMuc");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WikiService.DichVuWiki")]
    public interface DichVuWiki {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangNhap", ReplyAction="http://tempuri.org/DichVuWiki/DangNhapResponse")]
        int DangNhap(WikiManageWeb.WikiService.TaiKhoan userCaContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangNhap", ReplyAction="http://tempuri.org/DichVuWiki/DangNhapResponse")]
        System.Threading.Tasks.Task<int> DangNhapAsync(WikiManageWeb.WikiService.TaiKhoan userCaContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdmin", ReplyAction="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdminResponse")]
        bool DangKiTaiKhoanAdmin(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdmin", ReplyAction="http://tempuri.org/DichVuWiki/DangKiTaiKhoanAdminResponse")]
        System.Threading.Tasks.Task<bool> DangKiTaiKhoanAdminAsync(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTaiKhoan", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTaiKhoanResponse")]
        WikiManageWeb.WikiService.TaiKhoan KiemTraTaiKhoan(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/KiemTraTaiKhoan", ReplyAction="http://tempuri.org/DichVuWiki/KiemTraTaiKhoanResponse")]
        System.Threading.Tasks.Task<WikiManageWeb.WikiService.TaiKhoan> KiemTraTaiKhoanAsync(WikiManageWeb.WikiService.TaiKhoan userContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachDanhMucResponse")]
        System.Collections.Generic.List<WikiManageWeb.WikiService.DanhMuc> DanhSachDanhMuc();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/DanhSachDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/DanhSachDanhMucResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<WikiManageWeb.WikiService.DanhMuc>> DanhSachDanhMucAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ThemMoiDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ThemMoiDanhMucResponse")]
        bool ThemMoiDanhMuc(WikiManageWeb.WikiService.DanhMuc category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DichVuWiki/ThemMoiDanhMuc", ReplyAction="http://tempuri.org/DichVuWiki/ThemMoiDanhMucResponse")]
        System.Threading.Tasks.Task<bool> ThemMoiDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DichVuWikiChannel : WikiManageWeb.WikiService.DichVuWiki, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DichVuWikiClient : System.ServiceModel.ClientBase<WikiManageWeb.WikiService.DichVuWiki>, WikiManageWeb.WikiService.DichVuWiki {
        
        public DichVuWikiClient() {
        }
        
        public DichVuWikiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DichVuWikiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWikiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DichVuWikiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DangNhap(WikiManageWeb.WikiService.TaiKhoan userCaContract) {
            return base.Channel.DangNhap(userCaContract);
        }
        
        public System.Threading.Tasks.Task<int> DangNhapAsync(WikiManageWeb.WikiService.TaiKhoan userCaContract) {
            return base.Channel.DangNhapAsync(userCaContract);
        }
        
        public bool DangKiTaiKhoanAdmin(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.DangKiTaiKhoanAdmin(userContract);
        }
        
        public System.Threading.Tasks.Task<bool> DangKiTaiKhoanAdminAsync(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.DangKiTaiKhoanAdminAsync(userContract);
        }
        
        public WikiManageWeb.WikiService.TaiKhoan KiemTraTaiKhoan(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.KiemTraTaiKhoan(userContract);
        }
        
        public System.Threading.Tasks.Task<WikiManageWeb.WikiService.TaiKhoan> KiemTraTaiKhoanAsync(WikiManageWeb.WikiService.TaiKhoan userContract) {
            return base.Channel.KiemTraTaiKhoanAsync(userContract);
        }
        
        public System.Collections.Generic.List<WikiManageWeb.WikiService.DanhMuc> DanhSachDanhMuc() {
            return base.Channel.DanhSachDanhMuc();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<WikiManageWeb.WikiService.DanhMuc>> DanhSachDanhMucAsync() {
            return base.Channel.DanhSachDanhMucAsync();
        }
        
        public bool ThemMoiDanhMuc(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.ThemMoiDanhMuc(category);
        }
        
        public System.Threading.Tasks.Task<bool> ThemMoiDanhMucAsync(WikiManageWeb.WikiService.DanhMuc category) {
            return base.Channel.ThemMoiDanhMucAsync(category);
        }
    }
}
